// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA5AXEf_8dT2dVwGiIQoyYtJ-i-StR8nxI',
    appId: '1:649358456338:web:423d616e2fb24da1714acb',
    messagingSenderId: '649358456338',
    projectId: 'storepost-a64b8',
    authDomain: 'storepost-a64b8.firebaseapp.com',
    storageBucket: 'storepost-a64b8.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCx6c4Fcxc1b7Ko9hpBq_l7kvivl_EWWfc',
    appId: '1:649358456338:android:320e38d276d1ad71714acb',
    messagingSenderId: '649358456338',
    projectId: 'storepost-a64b8',
    storageBucket: 'storepost-a64b8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyATSNAv_ac63GBynrg6JYwDl8QRozOGG5k',
    appId: '1:649358456338:ios:eab014fa4b7f2c8d714acb',
    messagingSenderId: '649358456338',
    projectId: 'storepost-a64b8',
    storageBucket: 'storepost-a64b8.firebasestorage.app',
    iosBundleId: 'com.example.ocamPos',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyATSNAv_ac63GBynrg6JYwDl8QRozOGG5k',
    appId: '1:649358456338:ios:eab014fa4b7f2c8d714acb',
    messagingSenderId: '649358456338',
    projectId: 'storepost-a64b8',
    storageBucket: 'storepost-a64b8.firebasestorage.app',
    iosBundleId: 'com.example.ocamPos',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA5AXEf_8dT2dVwGiIQoyYtJ-i-StR8nxI',
    appId: '1:649358456338:web:b1d08bed673f7d7b714acb',
    messagingSenderId: '649358456338',
    projectId: 'storepost-a64b8',
    authDomain: 'storepost-a64b8.firebaseapp.com',
    storageBucket: 'storepost-a64b8.firebasestorage.app',
  );
}
